### ISSUE TITLE
Enter, Exit, but not Tick or Update?

### ISSUE THREAD

**Issue by ghost** [furuholm/RxFsm#2]
Hello

I wonder why there are no Tick or Update events, only Enter and Exit

How do you update the logic then?

**Comment by furuholm** [comment]
Typically you would use some suitable RX operator to which you subscribe when you enter the state and unsubscribe to when you exit the state. In your case interval sounds like a good candidate http://reactivex.io/documentation/operators/interval.html

**Comment by ghost** [comment]
Awesome thanks a lot!
